import type { Initiative } from './definitions';

export const mockInitiatives: Initiative[] = [
  {
    id: '1',
    locationName: 'São Paulo, SP',
    latitude: -23.55,
    longitude: -46.63,
    evangelizedName: 'Maria',
    evangelistName: 'João',
    photoUrl: 'https://picsum.photos/seed/ev1/600/400',
    photoHint: 'smiling person',
    testimony: 'We had a wonderful conversation about faith on Paulista Avenue. Maria was very open and we prayed together. It was a beautiful moment.',
    interactionType: 'presentation',
    date: '2024-07-20',
  },
  {
    id: '2',
    locationName: 'Rio de Janeiro, RJ',
    latitude: -22.91,
    longitude: -43.17,
    evangelizedName: 'Carlos',
    evangelistName: 'Ana',
    photoUrl: 'https://picsum.photos/seed/ev2/600/400',
    photoHint: 'beach sunset',
    testimony: 'Shared the gospel with Carlos near Copacabana beach. He was moved by the message and accepted Jesus into his life! Glory to God!',
    interactionType: 'acceptance',
    date: '2024-07-21',
  },
  {
    id: '3',
    locationName: 'Belo Horizonte, MG',
    latitude: -19.92,
    longitude: -43.93,
    evangelizedName: 'Fernanda',
    evangelistName: 'Pedro',
    photoUrl: 'https://picsum.photos/seed/ev3/600/400',
    photoHint: 'city park',
    testimony: 'Just had a deep spiritual conversation with Fernanda at the Municipal Park. She is thinking deeply about what we discussed.',
    interactionType: 'conversation',
    date: '2024-07-19',
  },
    {
    id: '4',
    locationName: 'Vitória, ES',
    latitude: -20.32,
    longitude: -40.31,
    evangelizedName: 'Lucas',
    evangelistName: 'Sofia',
    photoUrl: 'https://picsum.photos/seed/ev4/600/400',
    photoHint: 'ocean view',
    testimony: 'Presented the plan of salvation to Lucas at Praia da Costa. He has many questions, and we will meet again next week.',
    interactionType: 'presentation',
    date: '2024-07-22',
  },
   {
    id: '5',
    locationName: 'Campinas, SP',
    latitude: -22.9071,
    longitude: -47.0633,
    evangelizedName: 'Juliana',
    evangelistName: 'Marcos',
    photoUrl: 'https://picsum.photos/seed/ev5/600/400',
    photoHint: 'university campus',
    testimony: 'Juliana, a university student, decided to follow Christ after we talked for an hour. We are now connecting her with a local church.',
    interactionType: 'acceptance',
    date: '2024-07-23',
  }
];
